# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            race_conditions
tagline:          'Coding and running'
description:      'Thoughts on software engineering and running from a newbie developer'
url:              http://winterflower.github.io

author:
  name:           'Camilla Montonen'
  url:

paginate:         5

# Custom vars
#version:          1.0.0

#github:
#  repo:           https://github.com/winterflower.github.io.git
