# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            thoughtwisps
tagline:          'One commit at a time'
description:      'Thoughtlets on software, maths, science and society'
url:              http://winterflower.github.io

author:
  name:           'Camilla Montonen'
  url:

paginate:         5

# Custom vars
#version:          1.0.0

#github:
#  repo:           https://github.com/winterflower.github.io.git
